spring.application.name=PRODUCTS-SERVICE
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# ImageKit
imagekit.id=mayuripatil
imagekit.url-endpoint=https://ik.imagekit.io/mayuripatil
imagekit.public-key=public_Qt1dL7VMh3w7f+xYFXIXpB/G1uc=
imagekit.private-key=private_3MbnEGv01ZheryRdKvwTzUQ5J5E=
imagekit.folder=/products

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true



